//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaApp.resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibliotecaApp.resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new author.
        /// </summary>
        public static string AddNewAuthor {
            get {
                return ResourceManager.GetString("AddNewAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new book.
        /// </summary>
        public static string AddNewBook {
            get {
                return ResourceManager.GetString("AddNewBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new category.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book already borrowed.
        /// </summary>
        public static string AlreadyBorrowedError {
            get {
                return ResourceManager.GetString("AlreadyBorrowedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding a new author.
        /// </summary>
        public static string AuthorError {
            get {
                return ResourceManager.GetString("AuthorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name is required.
        /// </summary>
        public static string AuthorNameRequired {
            get {
                return ResourceManager.GetString("AuthorNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author added succesfully.
        /// </summary>
        public static string AuthorSucces {
            get {
                return ResourceManager.GetString("AuthorSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Copies.
        /// </summary>
        public static string AvailableCopies {
            get {
                return ResourceManager.GetString("AvailableCopies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available copies is required.
        /// </summary>
        public static string AvailableCopiesRequired {
            get {
                return ResourceManager.GetString("AvailableCopiesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error when trying to add a new book. Please try again.
        /// </summary>
        public static string BookAddError {
            get {
                return ResourceManager.GetString("BookAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while processing. Try again later.
        /// </summary>
        public static string BookAddGenericError {
            get {
                return ResourceManager.GetString("BookAddGenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book was added succesfully!.
        /// </summary>
        public static string BookAddSuccess {
            get {
                return ResourceManager.GetString("BookAddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data is invalid. Please check the form and try again..
        /// </summary>
        public static string BookAddValidationError {
            get {
                return ResourceManager.GetString("BookAddValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is required.
        /// </summary>
        public static string BookTitleRequired {
            get {
                return ResourceManager.GetString("BookTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow.
        /// </summary>
        public static string Borrow {
            get {
                return ResourceManager.GetString("Borrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow Book.
        /// </summary>
        public static string BorrowBook {
            get {
                return ResourceManager.GetString("BorrowBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow Date.
        /// </summary>
        public static string BorrowDate {
            get {
                return ResourceManager.GetString("BorrowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrow date is required.
        /// </summary>
        public static string BorrowDateRequired {
            get {
                return ResourceManager.GetString("BorrowDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed books.
        /// </summary>
        public static string BorrowedBooks {
            get {
                return ResourceManager.GetString("BorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borrowed on.
        /// </summary>
        public static string BorrowedOn {
            get {
                return ResourceManager.GetString("BorrowedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book was borrowed succesfull.
        /// </summary>
        public static string BorrowSuccess {
            get {
                return ResourceManager.GetString("BorrowSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while adding a new category.
        /// </summary>
        public static string CategoryError {
            get {
                return ResourceManager.GetString("CategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is required.
        /// </summary>
        public static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category added succesfully.
        /// </summary>
        public static string CategorySucces {
            get {
                return ResourceManager.GetString("CategorySucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required.
        /// </summary>
        public static string CommentRequired {
            get {
                return ResourceManager.GetString("CommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Image.
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required.
        /// </summary>
        public static string DateOfBirthRequired {
            get {
                return ResourceManager.GetString("DateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete this book?.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF.
        /// </summary>
        public static string DownloadPDF {
            get {
                return ResourceManager.GetString("DownloadPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Book.
        /// </summary>
        public static string EditBook {
            get {
                return ResourceManager.GetString("EditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with this email already exists.
        /// </summary>
        public static string EmailExistsError {
            get {
                return ResourceManager.GetString("EmailExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be authenticated to be able to borrow a book!.
        /// </summary>
        public static string ErrorOnBorrow {
            get {
                return ResourceManager.GetString("ErrorOnBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Popular?.
        /// </summary>
        public static string IsPopular {
            get {
                return ResourceManager.GetString("IsPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Recommended?.
        /// </summary>
        public static string IsRecommended {
            get {
                return ResourceManager.GetString("IsRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password incorrect. Please try again!.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters long..
        /// </summary>
        public static string MinLengthPassword {
            get {
                return ResourceManager.GetString("MinLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no copies available to borrow!.
        /// </summary>
        public static string NoAvailableCopiesError {
            get {
                return ResourceManager.GetString("NoAvailableCopiesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No borrowed books.
        /// </summary>
        public static string NoBorrowedBooks {
            get {
                return ResourceManager.GetString("NoBorrowedBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords does not match.
        /// </summary>
        public static string PasswordMatch {
            get {
                return ResourceManager.GetString("PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most popular books.
        /// </summary>
        public static string PopularBooks {
            get {
                return ResourceManager.GetString("PopularBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating is required.
        /// </summary>
        public static string RatingRequired {
            get {
                return ResourceManager.GetString("RatingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one letter and one number..
        /// </summary>
        public static string RegExError {
            get {
                return ResourceManager.GetString("RegExError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the account.
        /// </summary>
        public static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succesfully register!.
        /// </summary>
        public static string RegisterSuccess {
            get {
                return ResourceManager.GetString("RegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Return Date.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review date.
        /// </summary>
        public static string ReviewDate {
            get {
                return ResourceManager.GetString("ReviewDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review date is required.
        /// </summary>
        public static string ReviewDateRequired {
            get {
                return ResourceManager.GetString("ReviewDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        public static string Romanian {
            get {
                return ResourceManager.GetString("Romanian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search books.
        /// </summary>
        public static string SearchBooks {
            get {
                return ResourceManager.GetString("SearchBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an author.
        /// </summary>
        public static string SelectAuthor {
            get {
                return ResourceManager.GetString("SelectAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required.
        /// </summary>
        public static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Library.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while updating the book.
        /// </summary>
        public static string UpdateBookError {
            get {
                return ResourceManager.GetString("UpdateBookError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book updated succesfully!.
        /// </summary>
        public static string UpdateBookSuccess {
            get {
                return ResourceManager.GetString("UpdateBookSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserExistsError {
            get {
                return ResourceManager.GetString("UserExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
    }
}
